extend type Mutation {
    consentCreate(spexareId: ID!, typeId: ID!, input: ConsentCreate!): Consent
    consentUpdate(spexareId: ID!, typeId: ID!, input: ConsentUpdate!): Consent
    consentDelete(spexareId: ID!, typeId: ID!, id: ID!): Void
}

type Consent {
    id: ID!
    value: Boolean!
    type: Type!
    createdBy: String!
    createdAt: Instant!
    lastModifiedBy: String
    lastModifiedAt: Instant
}

type ConsentConnection {
    edges: [ConsentEdge]!
    pageInfo: PageInfo!
    totalCount: Int!
}

type ConsentEdge {
    cursor: String!
    node: Consent!
}

input ConsentCreate {
    value: Boolean!
}

input ConsentUpdate {
    id: ID!
    value: Boolean!
}