extend type Query {
    jobStatus(id: ID!): JobStatus
    job(id: ID!): Job
    jobs: [Job]
}

extend type Subscription {
    jobProgress(id: ID!): JobStatus
}

type JobReference {
    id: ID!
}

type Job {
    id: ID!
    name: String!
    status: String!
    exitStatus: String
    createdAt: Instant
    startedAt: Instant
    finishedAt: Instant
    hasDownload: Boolean
    importResult: ImportResult
}

type JobStatus {
    id: ID!
    name: String!
    status: String!
    exitStatus: String
}

type ImportResult {
    success: Boolean!
    errors: [String]
    messages: [String]
    data: JSON
}
