extend type Mutation {
    membershipCreate(spexareId: ID!, typeId: ID!, input: MembershipCreate!): Membership
    membershipDelete(spexareId: ID!, typeId: ID!, id: ID!): Void
}

type Membership {
    id: ID!
    year: Year!
    type: Type!
    createdBy: String!
    createdAt: Instant!
    lastModifiedBy: String
    lastModifiedAt: Instant
}

type MembershipConnection {
    edges: [MembershipEdge]!
    pageInfo: PageInfo!
}

type MembershipEdge {
    cursor: String!
    node: Membership!
}

input MembershipCreate {
    year: Year!
}
