extend type Query {
    newsPaged(first: Int, after: String, last: Int, before: String, filter: String = "published:TRUE", sort: [String] = ["visibleFrom"], direction: SortDirection = ASC): NewsConnection
    news(id: ID!): News
    newsEvents(sourceId: ID!, sinceInDays: Int = 90): [Event]
    newsExport(ids: [ID], filter: String, type: ExportType!): JobReference
}

extend type Mutation {
    newsCreate(input: NewsCreate!): News
    newsUpdate(input: NewsUpdate!): News
    newsDelete(id: ID!): Void
}

type News {
    id: ID!
    subject: String!
    text: String!
    visibleFrom: Date
    visibleTo: Date
    published: Boolean
    createdBy: String!
    createdAt: Instant!
    lastModifiedBy: String
    lastModifiedAt: Instant
}

type NewsConnection {
    edges: [NewsEdge]!
    pageInfo: PageInfo!
}

type NewsEdge {
    cursor: String!
    node: News!
}

input NewsCreate {
    subject: String!
    text: String!
    visibleFrom: Date
    visibleTo: Date
}

input NewsUpdate {
    id: ID!
    subject: String!
    text: String!
    visibleFrom: Date
    visibleTo: Date
}
