extend type Query {
    tagPaged(first: Int, after: String, last: Int, before: String, filter: String = "", sort: [String] = ["name"], direction: SortDirection = ASC): TagConnection
    tag(id: ID!): Tag
    tagEvents(sourceId: ID!, sinceInDays: Int = 90): [Event]
    tagExport(ids: [ID], filter: String, type: ExportType!): JobReference
}

extend type Mutation {
    tagCreate(input: TagCreate!): Tag
    tagUpdate(input: TagUpdate!): Tag
    tagDelete(id: ID!): Void
}

type Tag {
    id: ID!
    name: String!
    createdBy: String!
    createdAt: Instant!
    lastModifiedBy: String
    lastModifiedAt: Instant
}

type TagConnection {
    edges: [TagEdge]!
    pageInfo: PageInfo!
}

type TagEdge {
    cursor: String!
    node: Tag!
}

input TagCreate {
    name: String!
}

input TagUpdate {
    id: ID!
    name: String!
}
