extend type Query {
    taskPaged(first: Int, after: String, last: Int, before: String, filter: String = "", sort: [String] = ["name"], direction: SortDirection = ASC): TaskConnection
    task(id: ID!): Task
    taskEvents(sourceId: ID!, sinceInDays: Int = 90): [Event]
    taskExport(ids: [ID], filter: String, type: ImpexType!): JobReference
}

extend type Mutation {
    taskCreate(input: TaskCreate!): Task
    taskUpdate(input: TaskUpdate!): Task
    taskDelete(id: ID!): Void
    taskCategoryAdd(taskId: ID!, id: ID!): Void
    taskCategoryRemove(taskId: ID!): Void
}

type Task {
    id: ID!
    name: String!
    category: TaskCategory
    createdBy: String!
    createdAt: Instant!
    lastModifiedBy: String
    lastModifiedAt: Instant
}

type TaskConnection {
    edges: [TaskEdge]!
    pageInfo: PageInfo!
    totalCount: Int!
}

type TaskEdge {
    cursor: String!
    node: Task!
}

input TaskCreate {
    name: String!
}

input TaskUpdate {
    id: ID!
    name: String!
}
