management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

spring:
  jpa:
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED

  servlet:
    multipart:
      max-file-size: 15MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

spexregister:
  default-language: sv
  languages:
    - en
    - sv
  crypto:
    secret-key: ${SECRET_KEY}
    initialization-vector: ${IV}
    algorithm: "AES/CFB/PKCS5Padding"
