spring:
  config:
    import: "optional:configtree:/run/secrets/"
  datasource:
    password: ${MYSQL_APP_USER_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
        search:
          backend:
            type: lucene
            lucene_version: LATEST
            directory:
              type: local-filesystem
              root: ./data/index_data
          schema_management:
            strategy: create-or-update
          indexing:
            listeners:
              enabled: true
  servlet:
    multipart:
      max-file-size: 15MB
  task:
    scheduling:
      pool:
        size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

server:
  port: 8080

logging:
  file:
    path: ./data/log_data

spexregister:
  default-language: sv
  languages:
    - en
    - sv
  crypto:
    secret-key: ${APP_SECRET_KEY}
    initialization-vector: ${APP_IV}
    algorithm: "AES/CFB/PKCS5Padding"
  jobs:
    full-index:
      cron-expression: 0 0 2 * * ? # Every night at 02:00
    publish-unpublish-news:
      cron-expression: 5 0 0 * * ? # Every night at 00:00:05
    sync-users:
      cron-expression: 0 0 1 * * ? # Every night at 01:00
  keycloak:
    url: ${APP_KEYCLOAK_URL}
    realm: ${APP_KEYCLOAK_REALM}
    admin:
      client-id: ${APP_KEYCLOAK_ADMIN_CLIENT_ID}
      client-secret: ${APP_KEYCLOAK_ADMIN_CLIENT_SECRET}
    client:
      client-id: ${APP_KEYCLOAK_CLIENT_CLIENT_ID}
  sample-data:
    import: ${APP_IMPORT_SAMPLE_DATA}