management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

spring:
  jpa:
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        search:
          backend:
            type: lucene
            lucene_version: LATEST
            directory:
              type: local-filesystem
              root: ./.index
          schema_management:
            strategy: create-or-update
          indexing:
            listeners:
              enabled: true

  datasource:
    url: jdbc:mysql://192.168.1.55:3307/spexregister
    username: root
    password: Gammabetaalpha314

  servlet:
    multipart:
      max-file-size: 15MB

  task:
    scheduling:
      pool:
        size: 5

  flyway:
    table: flyway_schema_history_spexregister
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  threads:
    virtual:
      enabled: true

spexregister:
  default-language: sv
  languages:
    - en
    - sv
  crypto:
    secret-key: ${SECRET_KEY}
    initialization-vector: ${IV}
    algorithm: "AES/CFB/PKCS5Padding"
  jobs:
    full-index:
      cron-expression: 0 0 2 * * ? # Every night at 02:00
    publish-unpublish-news:
      cron-expression: 5 0 0 * * ? # Every night at 00:00:05
  default-password-encoder-prefix: "bcrypt"
  password-encodings:
    bcrypt:
      settings:
        strength: 10