management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

spring:
  jpa:
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED

  servlet:
    multipart:
      max-file-size: 10MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
