management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

spring:
  jpa:
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        search:
          backend:
            type: lucene
            lucene_version: LATEST
            directory:
              type: local-filesystem
              root: ./.index
          schema_management:
            strategy: create-or-update
          indexing:
            listeners:
              enabled: true

  datasource:
    url: TODO
    username: TODO
    password: TODO

  servlet:
    multipart:
      max-file-size: 15MB

  task:
    scheduling:
      pool:
        size: 5

  flyway:
    table: flyway_schema_history_spexregister
    locations: classpath:db/migration,classpath:nu/fgv/register/server/util/migration
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  threads:
    virtual:
      enabled: true

server:
  port: 8081

spexregister:
  default-language: sv
  languages:
    - en
    - sv
  crypto:
    secret-key: ${SECRET_KEY}
    initialization-vector: ${IV}
    algorithm: "AES/CFB/PKCS5Padding"
  jobs:
    full-index:
      cron-expression: 0 0 2 * * ? # Every night at 02:00
    publish-unpublish-news:
      cron-expression: 5 0 0 * * ? # Every night at 00:00:05
    sync-users:
      cron-expression: 0 0 1 * * ? # Every night at 01:00
  keycloak:
    url: ${KEYCLOAK_URL}
    realm: ${KEYCLOAK_REALM}
    admin:
      client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
      client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
    client:
      client-id: ${KEYCLOAK_CLIENT_CLIENT_ID}