query spexPaged ($first: Int = 10, $filter: String = "") {
    spexPaged (first: $first, filter: $filter) {
        edges {
            cursor
            node {
                id
                year
                title
                revival
                parent {
                    id
                    year
                    createdBy
                    createdAt
                    lastModifiedBy
                    lastModifiedAt
                }
                posterUrl
                category {
                    id
                    name
                    firstYear
                    logoUrl
                    createdBy
                    createdAt
                    lastModifiedBy
                    lastModifiedAt
                }
                revivalsPaged (first: $first) {
                    edges {
                        cursor
                        node {
                            id
                            year
                            createdBy
                            createdAt
                            lastModifiedBy
                            lastModifiedAt
                        }
                    }
                    pageInfo {
                        hasPreviousPage
                        hasNextPage
                        startCursor
                        endCursor
                    }
                    totalCount
                }
                revivals {
                    id
                    year
                    createdBy
                    createdAt
                    lastModifiedBy
                    lastModifiedAt
                }
                createdBy
                createdAt
                lastModifiedBy
                lastModifiedAt
            }
        }
        pageInfo {
            hasPreviousPage
            hasNextPage
            startCursor
            endCursor
        }
        totalCount
    }
}
