query taskActivityPaged ($spexareId: ID!, $activityId: ID!, $first: Int = 10) {
    taskActivityPaged (spexareId: $spexareId, activityId: $activityId, first: $first) {
        edges {
            cursor
            node {
                id
                task {
                    id
                    name
                    category {
                        id
                        name
                        actorPresent
                        createdBy
                        createdAt
                        lastModifiedBy
                        lastModifiedAt
                    }
                    createdBy
                    createdAt
                    lastModifiedBy
                    lastModifiedAt
                }
                actorsPaged(first: $first) {
                    edges {
                        cursor
                        node {
                            id
                            role
                            vocal {
                                id
                                label
                            }
                            createdBy
                            createdAt
                            lastModifiedBy
                            lastModifiedAt
                        }
                    }
                    pageInfo {
                        hasPreviousPage
                        hasNextPage
                        startCursor
                        endCursor
                    }
                }
                actors {
                    id
                    role
                    vocal {
                        id
                        label
                    }
                    createdBy
                    createdAt
                    lastModifiedBy
                    lastModifiedAt
                }
                createdBy
                createdAt
                lastModifiedBy
                lastModifiedAt
            }
        }
        pageInfo {
            hasPreviousPage
            hasNextPage
            startCursor
            endCursor
        }
    }
}
