query revisionFeedPaged ($first: Int, $after: String, $type: AuditedType, $modifiedBy: [String!], $sources: [AuditSource!], $from: Date, $to: Date, $sinceInDays: Int) {
    revisionFeedPaged (first: $first, after: $after, type: $type, modifiedBy: $modifiedBy, sources: $sources, from: $from, to: $to, sinceInDays: $sinceInDays) {
        edges {
            cursor
            node {
                revision
                modifiedAt
                modifiedBy
                types
                source
                operation
                comment
            }
        }
        pageInfo {
            hasPreviousPage
            hasNextPage
            startCursor
            endCursor
        }
        totalCount
    }
}
