query addressPaged ($spexareId: ID!, $first: Int = 10, $filter: String = "") {
    addressPaged (spexareId: $spexareId, first: $first, filter: $filter) {
        edges {
            cursor
            node {
                id
                streetAddress
                postalCode
                city
                country
                phone
                phoneMobile
                emailAddress
                type {
                    id
                    label
                    type
                }
                createdBy
                createdAt
                lastModifiedBy
                lastModifiedAt
            }
        }
        pageInfo {
            hasPreviousPage
            hasNextPage
            startCursor
            endCursor
        }
    }
}
