-- Task categories
INSERT INTO task_category (name, has_actor, created_by, created_at)
VALUES ('Kommitté', 0, 'system', CURRENT_TIME);
SET
@task_category_kommitte = LAST_INSERT_ID();

INSERT INTO task_category (name, has_actor, created_by, created_at)
VALUES ('Orkester', 0, 'system', CURRENT_TIME);
SET
@task_category_orkester = LAST_INSERT_ID();

INSERT INTO task_category (name, has_actor, created_by, created_at)
VALUES ('Ensemble', 1, 'system', CURRENT_TIME);
SET
@task_category_ensemble = LAST_INSERT_ID();

INSERT INTO task_category (name, has_actor, created_by, created_at)
VALUES ('Bandet', 0, 'system', CURRENT_TIME);
SET
@task_category_bandet = LAST_INSERT_ID();

-- Tasks
INSERT INTO task (name, category_id, created_by, created_at)
VALUES ('Affisch', @task_category_annat, 'system', CURRENT_TIME),
       ('Altsaxofon', @task_category_bandet, 'system', CURRENT_TIME),
       ('Altsaxofon', @task_category_symphonin, 'system', CURRENT_TIME),
       ('Arkitekt', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Arrangör', @task_category_annat, 'system', CURRENT_TIME),
       ('Bas', @task_category_orkester, 'system', CURRENT_TIME),
       ('Bas', @task_category_bandet, 'system', CURRENT_TIME),
       ('Bas', @task_category_symphonin, 'system', CURRENT_TIME),
       ('Basklarinett', @task_category_orkester, 'system', CURRENT_TIME),
       ('Bastuba', @task_category_orkester, 'system', CURRENT_TIME),
       ('Blockflöjt', @task_category_orkester, 'system', CURRENT_TIME),
       ('Casseur', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Communicateur', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Cello', @task_category_orkester, 'system', CURRENT_TIME),
       ('Cello', @task_category_bandet, 'system', CURRENT_TIME),
       ('Cello 1', @task_category_orkester, 'system', CURRENT_TIME),
       ('Cello 2', @task_category_orkester, 'system', CURRENT_TIME),
       ('Chanteuse', @task_category_ensemble, 'system', CURRENT_TIME),
       ('Conducteur', @task_category_ensemble, 'system', CURRENT_TIME),
       ('Costumeur', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Costumeurchef', @task_category_kommitte, 'system', CURRENT_TIME),
       ('CR-chef', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Dekoratör', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Designer', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Directeur', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Directeursassistent', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Documentateur', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Dragspel', @task_category_bandet, 'system', CURRENT_TIME),
       ('Elfiol', @task_category_bandet, 'system', CURRENT_TIME),
       ('Ensemblist', @task_category_ensemble, 'system', CURRENT_TIME),
       ('Exspextor', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Fagott', @task_category_orkester, 'system', CURRENT_TIME),
       ('Festdirecteur', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Festnisse', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Festroddare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Fiol', @task_category_bandet, 'system', CURRENT_TIME),
       ('Flöjt', @task_category_orkester, 'system', CURRENT_TIME),
       ('Flöjt', @task_category_bandet, 'system', CURRENT_TIME),
       ('Fotografiker', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Författare', @task_category_annat, 'system', CURRENT_TIME),
       ('Gitarr', @task_category_orkester, 'system', CURRENT_TIME),
       ('Gitarr', @task_category_bandet, 'system', CURRENT_TIME),
       ('Gitarr', @task_category_symphonin, 'system', CURRENT_TIME),
       ('Horn', @task_category_orkester, 'system', CURRENT_TIME),
       ('Info-chef', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Inspextant', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Inspextor', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Inspextris', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Inspicient', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Inspicientassistent', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Kapellmästare', @task_category_orkester, 'system', CURRENT_TIME),
       ('Klarinett', @task_category_orkester, 'system', CURRENT_TIME),
       ('Klarinett', @task_category_bandet, 'system', CURRENT_TIME),
       ('Klarinett', @task_category_symphonin, 'system', CURRENT_TIME),
       ('Kommittéledamot', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Kommunikationsansvarig', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Konstnärlig ledare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Kontrabas', @task_category_orkester, 'system', CURRENT_TIME),
       ('Koreograf', @task_category_annat, 'system', CURRENT_TIME),
       ('Livestreamer', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Ljudmästare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Ljusmästare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Ljudroddare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Ljusroddare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Mandolin', @task_category_bandet, 'system', CURRENT_TIME),
       ('Mediamästare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Mediaansvarig', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Musikproducent', @task_category_annat, 'system', CURRENT_TIME),
       ('Oboe', @task_category_orkester, 'system', CURRENT_TIME),
       ('Oboe', @task_category_bandet, 'system', CURRENT_TIME),
       ('Oboeflöjt', @task_category_orkester, 'system', CURRENT_TIME),
       ('Okänt', @task_category_annat, 'system', CURRENT_TIME),
       ('Okänt', @task_category_orkester, 'system', CURRENT_TIME),
       ('Okänt', @task_category_bandet, 'system', CURRENT_TIME),
       ('Okänt', @task_category_symphonin, 'system', CURRENT_TIME),
       ('Organisateur', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Orkester', @task_category_orkester, 'system', CURRENT_TIME),
       ('PR-chef', @task_category_kommitte, 'system', CURRENT_TIME),
       ('PR/Info-stab', @task_category_kommitte, 'system', CURRENT_TIME),
       ('PR-roddare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Panblåsare', @task_category_orkester, 'system', CURRENT_TIME),
       ('Pianör', @task_category_orkester, 'system', CURRENT_TIME),
       ('Pianör', @task_category_bandet, 'system', CURRENT_TIME),
       ('Pianör', @task_category_symphonin, 'system', CURRENT_TIME),
       ('Producent', @task_category_annat, 'system', CURRENT_TIME),
       ('Regisseur', @task_category_annat, 'system', CURRENT_TIME),
       ('Saxofon', @task_category_orkester, 'system', CURRENT_TIME),
       ('Saxofon', @task_category_bandet, 'system', CURRENT_TIME),
       ('Scen', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Scenmästare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Scennisse', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Scenograf', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Scenroddare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Sekreterare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Skivkommitté', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Skräddare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Slagverk', @task_category_orkester, 'system', CURRENT_TIME),
       ('Sopransaxofon', @task_category_orkester, 'system', CURRENT_TIME),
       ('Spexmästare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Sufflör', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Sömmerska', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Tekniknisse', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Teknikroddare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Tenorsaxofon', @task_category_bandet, 'system', CURRENT_TIME),
       ('Trombon', @task_category_orkester, 'system', CURRENT_TIME),
       ('Trombon', @task_category_bandet, 'system', CURRENT_TIME),
       ('Trummor', @task_category_orkester, 'system', CURRENT_TIME),
       ('Trummor', @task_category_bandet, 'system', CURRENT_TIME),
       ('Trummor', @task_category_symphonin, 'system', CURRENT_TIME),
       ('Trumpet', @task_category_orkester, 'system', CURRENT_TIME),
       ('Trumpet', @task_category_bandet, 'system', CURRENT_TIME),
       ('Trumpet', @task_category_symphonin, 'system', CURRENT_TIME),
       ('Turnéchef', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Tvärflöjt', @task_category_orkester, 'system', CURRENT_TIME),
       ('Tvärflöjt', @task_category_symphonin, 'system', CURRENT_TIME),
       ('Upplysare', @task_category_kommitte, 'system', CURRENT_TIME),
       ('Valthorn', @task_category_orkester, 'system', CURRENT_TIME),
       ('Valthorn', @task_category_symphonin, 'system', CURRENT_TIME),
       ('Viola', @task_category_orkester, 'system', CURRENT_TIME),
       ('Violacello', @task_category_orkester, 'system', CURRENT_TIME),
       ('Violin', @task_category_orkester, 'system', CURRENT_TIME),
       ('Violin 1', @task_category_orkester, 'system', CURRENT_TIME),
       ('Violin 1', @task_category_symphonin, 'system', CURRENT_TIME),
       ('Violin 2', @task_category_orkester, 'system', CURRENT_TIME),
       ('Violin 2', @task_category_symphonin, 'system', CURRENT_TIME),
       ('Vistextförfattare', @task_category_annat, 'system', CURRENT_TIME);
