= Spex
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:favicon: /favicon.ico
:operation-http-request-title: Example request
:operation-http-response-title: Example response

xref:../api-guide.adoc[Back to API guide]

[[create]]
== Create

operation::spex-create[snippets='security,request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[get_paged]]
== Get (paged)

operation::spex-get-all-paged[snippets='security,request-headers,query-parameters,http-request,response-headers,response-fields,links,http-response']

For details on filtering, refer to this xref:../api-guide.adoc#filtering[section]

Default filtering is ``parent:NULL``, i.e. exclude any revivals.

[[get]]
== Get

operation::spex-get[snippets='security,request-headers,path-parameters,http-request,response-headers,response-fields,links,http-response']

[[update]]
== Update

operation::spex-update[snippets='security,request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[update_partial]]
== Update (partial)

operation::spex-update-partial[snippets='security,request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[delete]]
== Delete

operation::spex-delete[snippets='security,request-headers,path-parameters,http-request,http-response']

[[poster]]
== Poster

[[poster_get]]
=== Get

operation::spex-poster-get[snippets='security,request-headers,path-parameters,http-request,response-headers,http-response']

[[poster_update]]
=== Update

operation::spex-poster-add[snippets='security,request-headers,http-request,http-response']

[[poster_update_multipart]]
=== Update (multipart)

operation::spex-poster-add-multipart[snippets='security,request-headers,http-request,http-response']

[[poster_delete]]
=== Delete

operation::spex-poster-remove[snippets='security,request-headers,path-parameters,http-request,http-response']

[[revivals]]
== Revivals

[[revivals_get_all]]
=== Get all (paged)

operation::spex-revival-get-all[snippets='security,request-headers,query-parameters,http-request,response-headers,response-fields,http-response']

[[revivals_get_parent]]
=== Get parent

operation::spex-revival-get-parent[snippets='security,request-headers,path-parameters,http-request,response-headers,http-response']

[[revivals_get]]
=== Get

operation::spex-revival-get[snippets='security,request-headers,path-parameters,http-request,response-headers,http-response']

[[revivals_get_paged]]
=== Get (paged)

operation::spex-revival-get-2[snippets='security,request-headers,path-parameters,http-request,response-headers,http-response']

[[revivals_create]]
=== Create

operation::spex-revival-add[snippets='security,request-headers,path-parameters,http-request,response-headers,response-fields,links,http-response']

[[revivals_delete]]
=== Delete

operation::spex-revival-remove[snippets='security,request-headers,path-parameters,http-request,http-response']

[[category]]
== Category

[[category_get]]
=== Get

operation::spex-category-get[snippets='security,request-headers,path-parameters,http-request,response-fields,links,response-headers,http-response']

[[category_create]]
=== Create

operation::spex-category-add[snippets='security,request-headers,path-parameters,http-request,http-response']

[[category_delete]]
=== Delete

operation::spex-category-remove[snippets='security,request-headers,path-parameters,http-request,http-response']

[[events]]
== Events

[[events_get]]
=== Get

operation::spex-event-get[snippets='security,request-headers,query-parameters,http-request,response-headers,response-fields,http-response']

xref:../api-guide.adoc[Back to API guide]
