= Consent
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:favicon: /favicon.ico
:operation-http-request-title: Example request
:operation-http-response-title: Example response

xref:../api-guide.adoc[Back to API guide]

[[create]]
== Create

operation::spexare-consent-add[snippets='security,request-headers,path-parameters,http-request,response-headers,response-fields,links,http-response']

[[get_paged]]
== Get (paged)

operation::spexare-consent-get-all-paged[snippets='security,request-headers,path-parameters,query-parameters,http-request,response-headers,response-fields,links,http-response']

[[get]]
== Get

operation::spexare-consent-get[snippets='security,request-headers,path-parameters,http-request,response-headers,response-fields,links,http-response']

[[update]]
== Update

operation::spexare-consent-update[snippets='security,request-headers,path-parameters,http-request,http-response']

[[delete]]
== Delete

operation::spexare-consent-remove[snippets='security,request-headers,path-parameters,http-request,http-response']

xref:../api-guide.adoc[Back to API guide]
