= Spex
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:favicon: /favicon.ico
:operation-http-request-title: Example request
:operation-http-response-title: Example response

xref:../api-guide.adoc[Back to API guide]

[[create]]
== Create

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::spex-create[snippets='request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[get_paged]]
== Get (paged)

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
* EDITOR
* USER
!===

operation::spex-get-all-paged[snippets='request-headers,query-parameters,http-request,response-headers,response-fields,links,http-response']

For details on filtering, refer to this xref:../api-guide.adoc#filtering[section]

[[get]]
== Get

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
* EDITOR
* USER
!===

operation::spex-get[snippets='request-headers,path-parameters,http-request,response-headers,response-fields,links,http-response']

[[update]]
== Update

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
* EDITOR
!===

operation::spex-update[snippets='request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[update_partial]]
== Update (partial)

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
* EDITOR
!===

operation::spex-update-partial[snippets='request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[delete]]
== Delete

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::spex-delete[snippets='request-headers,path-parameters,http-request,http-response']

[[poster]]
== Poster

[[poster_get]]
=== Get

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
* EDITOR
* USER
!===

operation::spex-poster-get[snippets='request-headers,path-parameters,http-request,response-headers,http-response']

[[poster_update]]
=== Update

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::spex-poster-add[snippets='request-headers,http-request,http-response']

[[poster_update_multipart]]
=== Update (multipart)

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::spex-poster-add-multipart[snippets='request-headers,http-request,http-response']

[[poster_delete]]
=== Delete

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
* EDITOR
!===

operation::spex-poster-remove[snippets='request-headers,path-parameters,http-request,http-response']

[[revivals]]
== Revivals

[[revivals_get_all]]
=== Get all (paged)

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
* EDITOR
* USER
!===

operation::spex-revival-get-all[snippets='request-headers,query-parameters,http-request,response-headers,response-fields,http-response']

[[revivals_get_parent]]
=== Get parent

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
* EDITOR
* USER
!===

operation::spex-revival-get-parent[snippets='request-headers,path-parameters,http-request,response-headers,http-response']

[[revivals_get]]
=== Get

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
* EDITOR
* USER
!===

operation::spex-revival-get[snippets='request-headers,path-parameters,http-request,response-headers,http-response']

[[revivals_get_paged]]
=== Get (paged)

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
* EDITOR
* USER
!===

operation::spex-revival-get-2[snippets='request-headers,path-parameters,http-request,response-headers,http-response']

[[revivals_create]]
=== Create

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
* EDITOR
!===

operation::spex-revival-add[snippets='request-headers,path-parameters,http-request,response-headers,response-fields,links,http-response']

[[revivals_delete]]
=== Delete

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
* EDITOR
!===

operation::spex-revival-remove[snippets='request-headers,path-parameters,http-request,http-response']

[[category]]
== Category

[[category_get]]
=== Get

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
* EDITOR
* USER
!===

operation::spex-category-get[snippets='request-headers,path-parameters,http-request,response-fields,links,response-headers,http-response']

[[category_create]]
=== Create

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::spex-category-add[snippets='request-headers,path-parameters,http-request,http-response']

[[category_delete]]
=== Delete

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::spex-category-remove[snippets='request-headers,path-parameters,http-request,http-response']

[[events]]
== Events

[[events_get]]
=== Get

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::spex-event-get[snippets='request-headers,query-parameters,http-request,response-headers,response-fields,http-response']

xref:../api-guide.adoc[Back to API guide]
