= Spex category
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:favicon: /favicon.ico
:operation-http-request-title: Example request
:operation-http-response-title: Example response

xref:../api-guide.adoc[Back to API guide]

[[create]]
== Create

operation::spex-category-create[snippets='security,request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[create_import]]
== Create/update/delete via import

operation::spex-category-create-import[snippets='security,request-headers,http-request,response-fields,http-response']

[[get_paged]]
== Get (paged)

operation::spex-category-get-all-paged[snippets='security,request-headers,query-parameters,http-request,response-headers,response-fields,links,http-response']

For details on filtering, refer to this xref:../api-guide.adoc#filtering[section]

[[get_export]]
== Get (export)

operation::spex-category-get-export[snippets='security,query-parameters,http-request,response-fields,http-response']

[[get]]
== Get

operation::spex-category-get-2[snippets='security,request-headers,path-parameters,http-request,response-headers,response-fields,links,http-response']

[[update]]
== Update

operation::spex-category-update[snippets='security,request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[update_partial]]
== Update (partial)

operation::spex-category-update-partial[snippets='security,request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[delete]]
== Delete

operation::spex-category-delete[snippets='security,request-headers,path-parameters,http-request,http-response']

[[logo]]
== Logo

[[logo_get]]
=== Get

operation::spex-category-logo-get[snippets='security,request-headers,path-parameters,http-request,response-headers,http-response']

[[logo_update]]
=== Update

operation::spex-category-logo-add[snippets='security,request-headers,http-request,http-response']

[[logo_update_multipart]]
== Update (multipart)

operation::spex-category-logo-add-multipart[snippets='security,request-headers,http-request,http-response']

[[events]]
== Events

[[events_get]]
=== Get

operation::spex-category-event-get[snippets='security,request-headers,query-parameters,http-request,response-headers,response-fields,http-response']

xref:../api-guide.adoc[Back to API guide]
