= Task
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:favicon: /favicon.ico
:operation-http-request-title: Example request
:operation-http-response-title: Example response

xref:../api-guide.adoc[Back to API guide]

[[create]]
== Create

operation::task-create[snippets='security,request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[create_import]]
== Create/update/delete via import

operation::task-create-import[snippets='security,request-headers,http-request,response-fields,http-response']

[[get_paged]]
== Get (paged)

operation::task-get-all-paged[snippets='security,request-headers,query-parameters,http-request,response-headers,response-fields,links,http-response']

For details on filtering, refer to this xref:../api-guide.adoc#filtering[section]

[sidebar]
.NOTE
--
It is also possible to filter tasks by category.
Use ``category.<category field>``.
--

[[get_export]]
== Get (export)

operation::task-get-export[snippets='security,query-parameters,http-request,response-fields,http-response']

[[get]]
== Get

operation::task-get[snippets='security,request-headers,path-parameters,http-request,response-headers,response-fields,links,http-response']

[[update]]
== Update

operation::task-update[snippets='security,request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[update_partial]]
== Update (partial)

operation::task-update-partial[snippets='security,request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[delete]]
== Delete

operation::task-delete[snippets='security,request-headers,path-parameters,http-request,http-response']

[[category]]
== Category

[[category_get]]
=== Get

operation::task-category-get[snippets='security,request-headers,path-parameters,http-request,response-fields,links,response-headers,http-response']

[[category_create]]
=== Create

operation::task-category-add[snippets='security,request-headers,path-parameters,http-request,http-response']

[[category_delete]]
=== Delete

operation::task-category-remove[snippets='security,request-headers,path-parameters,http-request,http-response']

[[events]]
== Events

[[events_get]]
=== Get

operation::task-event-get[snippets='security,request-headers,query-parameters,http-request,response-headers,response-fields,http-response']

xref:../api-guide.adoc[Back to API guide]
