= User
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:favicon: /favicon.ico
:operation-http-request-title: Example request
:operation-http-response-title: Example response

xref:../api-guide.adoc[Back to API guide]

[[create]]
== Create

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-create[snippets='request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[get_paged]]
== Get (paged)

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-get-all-paged[snippets='request-headers,query-parameters,http-request,response-headers,response-fields,links,http-response']

For details on filtering, refer to this xref:../api-guide.adoc#filtering[section]

[[get]]
== Get

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-get[snippets='request-headers,path-parameters,http-request,response-headers,response-fields,links,http-response']

[[update]]
== Update

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-update[snippets='request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[update_partial]]
== Update (partial)

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-update-partial[snippets='request-headers,request-fields,http-request,response-headers,response-fields,links,http-response']

[[delete]]
== Delete

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-delete[snippets='request-headers,path-parameters,http-request,http-response']

[[authority]]
== Authority

[[authority_get]]
=== Get

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-authority-get[snippets='request-headers,path-parameters,http-request,response-fields,response-headers,http-response']

[[authority_update]]
=== Update

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-authority-add[snippets='request-headers,path-parameters,http-request,http-response']

[[authority_update_multiple]]
=== Update (multiple)

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-authority-add-multiple[snippets='request-headers,path-parameters,query-parameters,http-request,http-response']

[[authority_delete]]
=== Delete

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-authority-remove[snippets='request-headers,path-parameters,http-request,http-response']

[[authority_delete_multiple]]
=== Delete (multiple)

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-authority-remove-multiple[snippets='request-headers,path-parameters,query-parameters,http-request,http-response']

[[state]]
== State

[[state_get]]
=== Get

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-state-get[snippets='request-headers,path-parameters,http-request,response-fields,response-headers,http-response']

[[state_update]]
=== Update

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-state-update[snippets='request-headers,path-parameters,http-request,http-response']

[[spexare]]
== Spexare

[[spexare_get]]
=== Get

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-spexare-get[snippets='request-headers,path-parameters,http-request,response-fields,response-headers,http-response']

[[spexare_update]]
=== Update

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-spexare-add[snippets='request-headers,path-parameters,http-request,http-response']

[[spexare_delete]]
=== Delete

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-spexare-remove[snippets='request-headers,path-parameters,http-request,http-response']

[[events]]
== Events

[[events_get]]
=== Get

!===
|Requires authentication|Yes
|Required roles
a|
* ADMIN
!===

operation::user-event-get[snippets='request-headers,query-parameters,http-request,response-headers,response-fields,http-response']

xref:../api-guide.adoc[Back to API guide]
