INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('HOME', 'ADDRESS', '{ "en": "Home", "sv": "Hem" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('WORK', 'ADDRESS', '{ "en": "Work", "sv": "Arbete" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('OTHER', 'ADDRESS', '{ "en": "Other", "sv": "Annat" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('CIRCULARS', 'CONSENT', '{ "en": "Circulars", "sv": "Utskick" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('EMAIL_CIRCULARS', 'CONSENT', '{ "en": "Email circulars", "sv": "Utskick via email" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('CING', 'MEMBERSHIP', '{ "en": "CING", "sv": "CING" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('FGV', 'MEMBERSHIP', '{ "en": "FGV", "sv": "FGV" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('UNKNOWN', 'VOCAL', '{ "en": "Unknown", "sv": "Okänt" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('B1', 'VOCAL', '{ "en": "B1", "sv": "B1" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('B2', 'VOCAL', '{ "en": "B2", "sv": "B2" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('T1', 'VOCAL', '{ "en": "T1", "sv": "T1" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('T2', 'VOCAL', '{ "en": "T2", "sv": "T2" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('S1', 'VOCAL', '{ "en": "S1", "sv": "S1" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('S2', 'VOCAL', '{ "en": "S2", "sv": "S2" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('A1', 'VOCAL', '{ "en": "A1", "sv": "A1" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('A2', 'VOCAL', '{ "en": "A2", "sv": "A2" }', 'system', CURRENT_DATE(), 0);
INSERT INTO type (id, type, labels, created_by, created_at, version) VALUES ('CHALMERS_STUDENT', 'TOGGLE', '{ "en": "Student at Chalmers", "sv": "Chalmersstudent" }', 'system', CURRENT_DATE(), 0);
