query NewsPagedCursor ($first: Int, $after: String, $last: Int, $before: String, $filter: String = "", $sort: [String] = ["id"], $direction: SortDirection = ASC) {
    newsPaged (first: $first, after: $after, last: $last, before: $before, filter: $filter, sort: $sort, direction: $direction) {
        edges {
            cursor
            node {
                id
                subject
            }
        }
        pageInfo {
            hasPreviousPage
            hasNextPage
            startCursor
            endCursor
        }
        totalCount
    }
}
