query actorPaged ($spexareId: ID!, $activityId: ID!, $taskActivityId: ID!, $first: Int = 10, $filter: String = "") {
    actorPaged (spexareId: $spexareId, activityId: $activityId, taskActivityId: $taskActivityId, first: $first, filter: $filter) {
        edges {
            cursor
            node {
                id
                role
                vocal {
                    id
                    label
                }
                createdBy
                createdAt
                lastModifiedBy
                lastModifiedAt            }
        }
        pageInfo {
            hasPreviousPage
            hasNextPage
            startCursor
            endCursor
        }
    }
}
